name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        poetry-version: [1.1.4]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry ${{ matrix.poetry-version }}
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==${{ matrix.poetry-version }}

    - name: View poetry --help
      run: |
        poetry --help

    - name: Install dependencies
      shell: bash
      run: python -m poetry install

    # - name: Lint check
    #   shell: bash -l {0}
    #   run: |
    #     poetry run isort --check --diff maps tests
    #     poetry run flake8 -v --statistics --count .
    #     poetry run black -l 99 --diff --check maps tests

    - name: Test with pytest
      env:
        HERE_APIKEY: ${{ secrets.HERE_APIKEY }}
        TOMTOM_APIKEY: ${{ secrets.TOMTOM_APIKEY }}
        MAPBOX_APIKEY: ${{ secrets.MAPBOX_APIKEY }}
        ORS_APIKEY: ${{ secrets.ORS_APIKEY }}
      run: |
        python -m poetry run python -m pytest -v --durations=10 --cov=maps tests --cov-report=xml
    - name: Upload coverage to Codecov
      if: github.ref == 'refs/heads/master' && matrix.python-version == '3.8'
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        verbose: true